### ISSUE TITLE
fix compute_ERC_h2

### ISSUE THREAD

**Issue by bonifazi** [bonifazi/Integration_EBV_and_GEBV#1]

**Comment by DamilolaDecarls** [comment]
Hey Renzo, I used this recently and found a few bugs in the `compute_ERC_h2` function. I have made the corrections on my local repository. It might be helpful to change it here as well

**Comment by bonifazi** [comment]
Hi @DamilolaDecarls, can you please link me to your repo or to the lines? I cannot find it in your profile (maybe it's a private one?).

**Comment by bonifazi** [comment]
@DamilolaDecarls, done! Thanks for the message and fix.

**Comment by bonifazi** [comment]
The documentation issue is now overlapping with the fixing one. Will move the documentation to a new one.
